name: Build Paper Plugin

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    # Maven 会根据 pom.xml 中新加的 https://repo.opencollab.dev/main/ 路径去搜索依赖
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: CoreLink-Plugin
        path: target/CoreLink.jar
