name: Build Paper Plugin

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    # 克隆并本地组装 20MB 的依赖环境
    - name: Build MCProtocolLib Locally
      run: |
        git clone https://github.com/GeyserMC/MCProtocolLib.git
        cd MCProtocolLib
        # 编译整个项目并安装到本地 Maven 仓库
        mvn clean install -DskipTests
        
    - name: Build Your Plugin
      run: mvn -B package --file pom.xml

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: CoreLink-Plugin
        path: target/CoreLink.jar
